
name: Deploy to Preview

on:
  workflow_dispatch:
  push:
    branches: [ migration-and-fixes ]
  pull_request:
    branches: [ migration-and-fixes ]

jobs:

  build:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pwabuilder.azurecr.io/pwabuilder-ios:dev
      
    - name: Login
      run: docker login pwabuilder.azurecr.io -u pwabuilder --password ${{secrets.azure}}
      
    - name: Push
      run: docker push pwabuilder.azurecr.io/pwabuilder-ios:dev
      
  build-pr:
    runs-on: ubuntu-latest
    if: github.event.name == 'pull_request'
    
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker Image for a PR
      run: docker build . --file Dockerfile
